### ISSUE TITLE
getConfig 用不了

### ISSUE THREAD

**Issue by Sligcm** [Tinywan/nacos-sdk-php#2]
调用 getConfig 提示：string(136) "{"timestamp":"2024-07-08T16:05:27.464+08:00","status":403,"error":"Forbidden","message":"user not found!","path":"/nacos/v1/cs/configs"}"
看了下 auth 的源代码，登录后也仅仅是给 auth 类增加了两个属性。
实际和 client 类毫无关系，和后续的 getConfig 也毫无关系。

**Comment by Tinywan** [comment]
你好，这个库好久没维护了。推荐你使用这个：https://github.com/workbunny/webman-nacos

**Comment by Sligcm** [comment]
> 你好，这个库好久没维护了。推荐你使用这个：https://github.com/workbunny/webman-nacos

好的，谢谢你。
